//https://www.youtube.com/watch?v=ZW9kOvjr7tU 6:44
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import BaseLayout from "../components/BaseLayer";
import Link from 'next/link';
import db from "../net/db";
import { collection, getDocs, query, where } from '@firebase/firestore';
import { useEffect, useState } from 'react';



const Home: NextPage = () => {

  const [list, setList] = useState([]);


  useEffect(() => {
    getDocs(query(collection(db, 'articles')))
      .then(results => {
        const newList = [];
        results.forEach(doc => {
          const data = doc.data();
          data.id = doc.id;
          newList.push(data);
        });
        setList(newList);
      })
  }, []);


  return (
    <BaseLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pb-4 mb-8 border-b">
        <Link href="/create">
          <button className="p-2 bg-black text-white">글쓰기</button>
        </Link>
      </div>


      <ul>
        {list.map(item => (
          <li key={item.id} className="flex flex-row w-full border-b p-2 mb-4" >
            <div className="text-lime-300">{item.subject}</div>
            <div className="w-64">{item.author}</div>
          </li>
        ))}

      </ul>

    </BaseLayout >
  )
}

export default Home;

